spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?user=postgres.bujiubgezonwxqejfuqu&password=cvrecruitment@12345
spring.datasource.username=postgres.bujiubgezonwxqejfuqu
spring.datasource.password=cvrecruitment@12345
spring.jpa.hibernate.ddl-auto=update
fastapi.service.base-url=http://localhost:8000
logging.file.name=logs/cv-recruitment.log
logging.level.com.cvrecruitment=INFO